(define (domain canopies_domain)
 (:requirements :typing :strips :non-deterministic)
 (:types location robot grape box)
 (:predicates (robot-at ?r - robot ?loc - location)
              (grape-at ?g - grape ?loc - location)
              (free ?r - robot)
              (support ?s - robot)
              (in_hand ?g - grape)
              (full ?b - box)
              (in ?b - box ?r - robot)
              (inside ?g - grape ?b - box)
              (adj ?x - location ?y - location)
              (ripe ?g - grape)(unripe ?g - grape)
              (cleared ?l - location) (unknown)
              (move_executed)
              (call_support_executed)
              (empty_box_executed)
              (check_grape_executed)
              (harvest_grape_executed)
              (drop_grape_executed)
              (handle_exception_executed)
              (assest_vine_executed)
              (unchecked ?l - location)
              )

    (:action move
        :parameters (?r - robot ?from - location ?to - location)
        :precondition (and (robot-at ?r ?from) (adj ?from ?to) (cleared ?from))
        :effect (and (robot-at ?r ?to) (not (robot-at ?r ?from))
              (move_executed)
              (not(call_support_executed))
              (not(empty_box_executed))
              (not(check_grape_executed))
              (not(harvest_grape_executed))
              (not(drop_grape_executed))
              (not(handle_exception_executed))
              (not(assest_vine_executed))
            )
    )

    (:action call_support
        :parameters (?r - robot ?from - location ?supp - robot)
        :precondition (and (support ?supp) (robot-at ?r ?from))
        :effect (and (robot-at ?supp ?from)
              (not(move_executed))
              (call_support_executed)
              (not(empty_box_executed))
              (not(check_grape_executed))
              (not(harvest_grape_executed))
              (not(drop_grape_executed))
              (not(handle_exception_executed))
              (not(assest_vine_executed))
            )
    )

    (:action empty_box
        :parameters (?r - robot ?supp - robot ?b - box ?from - location)
        :precondition (and (support ?supp) (in ?b ?r) (robot-at ?r ?from)
                        (robot-at ?supp ?from) (full ?b))
        :effect (and (not (full ?b)) (empty ?b)
        (not(move_executed))
              (not(call_support_executed))
              (empty_box_executed)
              (not(check_grape_executed))
              (not(harvest_grape_executed))
              (not(drop_grape_executed))
              (not(handle_exception_executed))
              (not(assest_vine_executed))
            )
    )

    (:action check_grape
        :parameters (?r - robot ?g - grape ?from - location)
        :precondition (and (robot-at ?r ?from) (grape-at ?g ?from) (unchecked ?from))
        :effect (and (oneof (ripe ?g) (unknown) (unripe ?g)) (not (unchecked ?from))
        (not(move_executed))
              (not(call_support_executed))
              (not(empty_box_executed))
              (check_grape_executed)
              (not(harvest_grape_executed))
              (not(drop_grape_executed))
              (not(handle_exception_executed))
              (not(assest_vine_executed))
            )
    )

    (:action harvest_grape
        :parameters (?r - robot ?g - grape ?b - box ?from - location)
        :precondition (and (ripe ?g) (free ?r) (robot-at ?r ?from)
                      (grape-at ?g ?from) (empty ?b) (in ?b ?r))
        :effect (and (not (free ?r)) (in_hand ?g)
              (not(move_executed))
              (not(call_support_executed))
              (not(empty_box_executed))
              (not(check_grape_executed))
              (harvest_grape_executed)
              (not(drop_grape_executed))
              (not(handle_exception_executed))
              (not(assest_vine_executed))
            )
    )

    (:action drop_grape
        :parameters (?r - robot ?g - grape ?b - box ?from - location)
        :precondition (and (in_hand ?g) (in ?b ?r) (robot-at ?r ?from))
        :effect (and (inside ?g ?b) (not (in_hand ?g)) (cleared ?from)(free ?r)
        (not(move_executed))
              (not(call_support_executed))
              (not(empty_box_executed))
              (not(check_grape_executed))
              (not(harvest_grape_executed))
              (drop_grape_executed)
              (not(handle_exception_executed))
              (not(assest_vine_executed))
            )
    )

    (:action handle_exception
        :parameters (?r - robot ?from - location)
        :precondition (and (robot-at ?r ?from) (unknown))
        :effect (and (cleared ?from) (not (unknown))
        (not(move_executed))
              (not(call_support_executed))
              (not(empty_box_executed))
              (not(check_grape_executed))
              (not(harvest_grape_executed))
              (not(drop_grape_executed))
              (handle_exception_executed)
              (not(assest_vine_executed))
            )
    )

    (:action assest_vine
        :parameters (?r - robot ?g - grape ?from - location)
        :precondition (and (unripe ?g) (robot-at ?r ?from) (grape-at ?g ?from))
        :effect (and (cleared ?from)
        (not(move_executed))
              (not(call_support_executed))
              (not(empty_box_executed))
              (not(check_grape_executed))
              (not(harvest_grape_executed))
              (not(drop_grape_executed))
              (not(handle_exception_executed))
              (assest_vine_executed)
            )
    )

)
